name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
    
jobs:
    deploy:
        runs-on: self-hosted
    
        strategy: 
            matrix:
                node-version: [12.x]
            
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0
                ref: main
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - name: Clean and install npm_modules
            run: |
                cd ./src/frontend
                rm -rf ./node_modules/
                npm install
        
          - name: Deploy site
            id: deploy
            run: |
                cd ./src/frontend
                npm run sudostart
            continue-on-error: true
                
          - name: Checking deployment
            id: serverkill
            if: steps.deploy.outcome != 'success'
            run: sudo pkill apache2
        
          - name: Attempt redeploy
            if: steps.serverkill.outcome == 'success'
            run: |
                cd ./src/frontend
                npm run sudostart
