name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
    
jobs:
    deploy:
        runs-on: self-hosted
    
        strategy: 
            matrix:
                node-version: [12.x]
            
        steps:
          - name: Reset working directory
            run: rm -rf *
            
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0
                ref: main
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - name: Clean and install npm_modules
            id: clean
            run: |
                cd ./src/frontend
                rm -rf ./node_modules/
                npm install
                sudo npm install forever -g
        
          - name: Deploy site
            id: deploy
            run: |
                cd ./src/frontend
                sudo forever stopall
                sudo forever start index.js
            continue-on-error: true

          - name: Check deploy
            id: check
            run: |
                sleep 5; sudo lsof -i :80 | grep node || exit 1
