name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
    
jobs:
    deploy:
        runs-on: self-hosted
    
        strategy: 
            matrix:
                node-version: [12.x]
            
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0
                ref: main
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
          - run: |
                cd ./src/frontend
                npm run sudostart
